# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
pod 'HandyJSON'
#pod 'SwiftyJSON'

pod 'SnapKit'
pod 'Alamofire'
pod 'ReactiveCocoa'
pod 'RxSwift', '~> 4.0'
pod 'RxCocoa'
pod 'RxDataSources', '~> 3.1.0'
pod 'Moya/RxSwift'
pod 'NSObject+Rx'



pod 'JSONModel'
#pod 'AFNetworking'
#pod 'Masonry'
pod 'SDAutoLayout'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'Bugly'
pod 'DZNEmptyDataSet'
pod 'IQKeyboardManager'
pod 'CYLTabBarController','~> 1.17.13'
pod 'WPAttributedMarkup'
#pod 'SDCycleScrollView'
#pod 'MLeaksFinder'
#pod 'TZImagePickerController'
pod 'PGDatePicker'  # Pods for test

end
